on:
  pull_request:
    paths:
      - .github/workflows/build.yml
      - src/**
      - xmake.lua
  push:
    paths:
      - .github/workflows/build.yml
      - src/**
      - xmake.lua
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: xmake-io/github-action-setup-xmake@v1

      - uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-
      
      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m release -p windows -v -y

      - run: |
          xmake -v -w -y

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-windows-x64-${{ github.sha }}
          path: |
            bin/

  check-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: |
          npm install clang-format@1.8.0

      - run: |
          npx clang-format --dry-run --Werror $(find src/ -type f -name '*.cpp' -o -name '*.h')
          