on:
  release:
    types:
      - published
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: xmake-io/github-action-setup-xmake@v1
      
      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m release -p windows -v -y

      - run: |
          xmake -w -y

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-windows-x64-${{ github.sha }}
          path: |
            bin/

  upload-to-release:
    needs:
      - build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-windows-x64-${{ github.sha }}
          path: release/

      - run: |
          cp COPYING COPYING.LESSER README.md release/

      - name: Archive release
        run: |
          cd release
          zip -r ../${{ github.event.repository.name }}-windows-x64.zip *
          cd ..

      - id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1

      - uses: softprops/action-gh-release@v1
        with:
          body: |
            ${{ steps.extract-release-notes.outputs.release_notes }}
          files: |
            ${{ github.event.repository.name }}-windows-x64.zip
